In [ ]:
import pandas as pd
import numpy as np

# Read the excel file containing 50.000 matches from 2000 to 2018
df = pd.read_excel('Datasets/2000-2018.xls')
#df = pd.read_csv('Datasets/2000-2018.csv', delimiter=',', encoding="utf-8-sig")
df.head()

In [51]:
# Replace all NaN with 0
df.fillna(0, inplace=True)

# Drop useless columns
to_drop = ['ATP', 'Location', 'Tournament']
df.drop(columns=to_drop, inplace=True)

# Rename columns with clearer names
to_rename={'Best of' : 'Nb sets max',
          'WRank' : 'Winner ranking',
          'LRank' : 'Loser ranking',
          'WPts' : 'Winner points',
          'LPts' : 'Loser points',
          'W1' : 'Games won by winner in set 1',
          'W2' : 'Games won by winner in set 2',
          'W3' : 'Games won by winner in set 3',
          'W4' : 'Games won by winner in set 4',
          'W5' : 'Games won by winner in set 5',
          'L1' : 'Games won by loser in set 1',
          'L2' : 'Games won by loser in set 2',
          'L3' : 'Games won by loser in set 3',
          'L4' : 'Games won by loser in set 4',
          'L5' : 'Games won by loser in set 5',
          'Wsets' : 'Winner sets',
          'Lsets' : 'Loser sets',
           'Comment' : 'Completed or retired'
          }
df.rename(columns=to_rename, inplace=True)
df.head()

,Date,Series,Court,Surface,Round,Nb sets max,Winner,Loser,Winner ranking,Loser ranking,...,Games won by loser in set 2,Games won by winner in set 3,Games won by loser in set 3,Games won by winner in set 4,Games won by loser in set 4,Games won by winner in set 5,Games won by loser in set 5,Winner sets,Loser sets,Completed or retired
0,2000-01-03,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,63,77,...,2,0,0,0.0,0.0,0.0,0.0,2.0,0,Completed
1,2000-01-03,International,Outdoor,Hard,1st Round,3,Enqvist T.,Clement A.,5,56,...,3,0,0,0.0,0.0,0.0,0.0,2.0,0,Completed
2,2000-01-03,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,40,655,...,5,6,3,0.0,0.0,0.0,0.0,2.0,1,Completed
3,2000-01-03,International,Outdoor,Hard,1st Round,3,Federer R.,Knippschild J.,65,87,...,4,0,0,0.0,0.0,0.0,0.0,2.0,0,Completed
4,2000-01-03,International,Outdoor,Hard,1st Round,3,Fromberg R.,Woodbridge T.,81,198,...,7,6,4,0.0,0.0,0.0,0.0,2.0,1,Completed

In [52]:
# Split the date
new = df["Date"].astype(str).str.split("-", n = 2, expand = True)
df["Year"] = new[0]
df["Month"] = new[1]
df.drop(columns=["Date"], inplace = True)
df.head()

,Series,Court,Surface,Round,Nb sets max,Winner,Loser,Winner ranking,Loser ranking,Games won by winner in set 1,...,Games won by loser in set 3,Games won by winner in set 4,Games won by loser in set 4,Games won by winner in set 5,Games won by loser in set 5,Winner sets,Loser sets,Completed or retired,Year,Month
0,International,Outdoor,Hard,1st Round,3,Dosedel S.,Ljubicic I.,63,77,6.0,...,0,0.0,0.0,0.0,0.0,2.0,0,Completed,2000,01
1,International,Outdoor,Hard,1st Round,3,Enqvist T.,Clement A.,5,56,6.0,...,0,0.0,0.0,0.0,0.0,2.0,0,Completed,2000,01
2,International,Outdoor,Hard,1st Round,3,Escude N.,Baccanello P.,40,655,6.0,...,3,0.0,0.0,0.0,0.0,2.0,1,Completed,2000,01
3,International,Outdoor,Hard,1st Round,3,Federer R.,Knippschild J.,65,87,6.0,...,0,0.0,0.0,0.0,0.0,2.0,0,Completed,2000,01
4,International,Outdoor,Hard,1st Round,3,Fromberg R.,Woodbridge T.,81,198,7.0,...,4,0.0,0.0,0.0,0.0,2.0,1,Completed,2000,01

In [ ]:
# Rearrange columns
cols = df.columns.tolist()
cols = cols[-1:] + cols[:-1]
df = df[cols]
df.head()

In [22]:
# Export to csv
df.to_csv('2000_2018.csv', sep=',', encoding='utf-8')